services:
  be_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    image: be-service
    container_name: be-service
    environment:
    - PORT=
    - APP_ENV=
    - DB_HOST=
    - DB_PORT=
    - DB_USERNAME=
    - DB_PASS=
    - DB_NAME=
    - DB_SSL_MODE=
    - ALLOWED_ORIGIN=
    env_file: ./deploy.env